name = "arthurr-portfolio-chatbot"
main = "src/index.js"
compatibility_date = "2026-06-01"

[vars]
ALLOWED_ORIGIN = "https://www.arthurr.gt.tc"

[[kv_namespaces]]
binding = "RATE_LIMIT_KV"
id = "7c3d842a5d45445b9c723db6a5d777ae"